site: pipefail.dev
title: pipefail.dev
keywords: blog, python, go, node.js, ruby, cloud, data, aws, gcp, kubernetes, docker
description: >-
  pipefail.dev
lang: en-US
timezone: America/Denver
repo: https://github.com/duffn/pipefail.dev
google_analytics: UA-60982925-6

author:
  name: duffn
  bio: I write about Python, Go, Node.js, Ruby,<br />cloud infrastructure, and data.
  picture: assets/images/gopher_avatar.png
  github: duffn
  mastodon: https://fosstodon.org/@duffn

url: "https://pipefail.dev"
baseurl: ""
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-minifier

jekyll-minifier:
  compress_css: false
  compress_json: false
  exclude: ["atom.xml", "sitemap.xml"]

paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
